GET http://localhost:5000/api/profiles?rm=rm1 HTTP/1.1

###

POST http://localhost:5000/api/profiles HTTP/1.1
content-type: application/json

{
    "name": "rm1",
    "email": "22"
}

###
GET http://bvme.azurewebsites.net/api/profiles

